// <auto-generated />
using BookishDB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BookishDB.Migrations
{
    [DbContext(typeof(BookishContext))]
    partial class BookishContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BookishDB.Models.BookViewModel", b =>
                {
                    b.Property<int>("BookID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BookID"));

                    b.Property<string>("Author")
                        .HasColumnType("text");

                    b.Property<int>("AvailableCopies")
                        .HasColumnType("integer");

                    b.Property<int?>("BookViewModelBookID")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<int>("TotalCopies")
                        .HasColumnType("integer");

                    b.HasKey("BookID");

                    b.HasIndex("BookViewModelBookID");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("BookishDB.Models.MemberBookViewModel", b =>
                {
                    b.Property<int>("MemberBookID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MemberBookID"));

                    b.Property<int>("BookID")
                        .HasColumnType("integer");

                    b.Property<int>("MemberID")
                        .HasColumnType("integer");

                    b.HasKey("MemberBookID");

                    b.HasIndex("BookID");

                    b.HasIndex("MemberID");

                    b.ToTable("MemberBooks");
                });

            modelBuilder.Entity("BookishDB.Models.MemberViewModel", b =>
                {
                    b.Property<int>("MemberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MemberID"));

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.HasKey("MemberID");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("BookishDB.Models.BookViewModel", b =>
                {
                    b.HasOne("BookishDB.Models.BookViewModel", null)
                        .WithMany("Books")
                        .HasForeignKey("BookViewModelBookID");
                });

            modelBuilder.Entity("BookishDB.Models.MemberBookViewModel", b =>
                {
                    b.HasOne("BookishDB.Models.BookViewModel", "Book")
                        .WithMany("MemberBooks")
                        .HasForeignKey("BookID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookishDB.Models.MemberViewModel", "Member")
                        .WithMany("MemberBooks")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("BookishDB.Models.BookViewModel", b =>
                {
                    b.Navigation("Books");

                    b.Navigation("MemberBooks");
                });

            modelBuilder.Entity("BookishDB.Models.MemberViewModel", b =>
                {
                    b.Navigation("MemberBooks");
                });
#pragma warning restore 612, 618
        }
    }
}
